apiVersion: v2
name: gpu-util-dashboard
description: "Drop-in GPU utilisation dashboard for NVIDIA clusters"
type: application
version: 0.1.0
appVersion: "1"
dependencies:
  # Prometheus for metrics
  - name: prometheus
    version: "25.20.0" # A recent stable version
    repository: "https://prometheus-community.github.io/helm-charts"
  # Grafana for visualization
  - name: grafana
    version: "9.2.1" # A recent stable version
    repository: "https://grafana.github.io/helm-charts"